### ISSUE TITLE
The about link is invalid

### ISSUE THREAD

**Issue by DaveParillo** [RunestoneInteractive/AuthorGuide#1]
Consider updating the about link in this repository from this:
https://runestoneinteractive.org/build/html/index.html
to this:
https://runestone.academy/runestone/static/authorguide/index.html

and making the same edit in README.md

**Comment by DaveParillo** [comment]
Thank you for updating the README.

The about link is still the outdated URL.

**Comment by bnmnetp** [comment]
fixed
