### ISSUE TITLE
conf.py is not found by `runestone build` command

### ISSUE THREAD

**Issue by DaveParillo** [RunestoneInteractive/AuthorGuide#2]
I was going to submit a PR to update the docs with some recent sunstone upgrades (I'm excited to try the SQL), but the project does not build - conf.py is missing.

Error from `Runestone build`

> $ runestone build
    Building with Runestone 5.0.8
    Traceback (most recent call last):
      File "/usr/local/bin/runestone", line 8, in <module>
        sys.exit(cli())
      File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
        return self.main(*args, **kwargs)
      File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
        rv = self.invoke(ctx)
      File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1289, in invoke
        rv.append(sub_ctx.command.invoke(sub_ctx))
      File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
        return callback(*args, **kwargs)
      File "/usr/local/lib/python3.8/site-packages/runestone/__main__.py", line 153, in build
        with open('conf.py', encoding='utf-8') as cf:
    FileNotFoundError: [Errno 2] No such file or directory: 'conf.py'

**Comment by bnmnetp** [comment]
The conf.py file is in the source folder.

**Comment by DaveParillo** [comment]
Is there a way to use it?

    cd source
    runestone build

still says `conf.py` not found:

>   File "/usr/local/lib/python3.8/site-packages/runestone/__main__.py", line 153, in build
    with open('conf.py', encoding='utf-8') as cf:
FileNotFoundError: [Errno 2] No such file or directory: 'conf.py'

**Comment by schweinsbergs** [comment]
Has this issue been resolved? It seems like the conf.py file was found, it just needs to be moved.

**Comment by DaveParillo** [comment]
Not for me, but honestly, I have not tried to reproduce lately.

**Comment by DaveParillo** [comment]
@schweinsbergs - yes, this issue is still open when building with Runestone 6.2.1.
I can "fix" this as follows:

1. move source/conf.py to repo root
2. modify conf.py
    ```
        diff conf.py source/conf.py
        19c19
         < from runestone import runestone_static_dirs, runestone_extensions, setup
         ---
         > from runestone import runestone_static_dirs, runestone_extensions
         33c33
         < templates_path = ['source/_templates']
         ---
         > templates_path = ['_templates']
         104c104
         < html_theme_path = ['source/_templates/plugin_layouts']
         ---
         > html_theme_path = ['_templates/plugin_layouts']
    ```
3. modify pavement.py
    ```
        @@ -25,7 +25,7 @@ options(
         builddir="./build/"+project_name,
         sourcedir="source",
         outdir="./build/"+project_name,
    -        confdir="source",
    +        confdir=".",
         project_name = project_name,
         template_args = {
             'course_id':project_name,
    ```

After these changes the build runs to completion with 26 warnings.
Most are simple rst syntax issues (invalid divid, etc).

Perhaps there is a command line combination or alternative build that precludes these shenanigans, but I do not know what that might be.

**Comment by bnmnetp** [comment]
Are you having this problem with one of the books from our repo or is this your own project?

The `runestone init` command sets things up for you so you should not have to worry about it.  All runestone does is use all of this to build up a sphinx-build command.  It would be helpful to see what the actual command is given your values in conf.py and pavement.py

**Comment by bnmnetp** [comment]
OK, it just hit me that the issue is when we are checking to see if you are importing setup and others from the runestone package.  But we are just assuming that conf.py is in the root -- where it normally is...

Its an easy fix now that I see the problem.

**Comment by DaveParillo** [comment]
@bnmnetp This issue is written against **this** repository.  

The build issue is related to building the book '[RunestoneInteractive/AuthorGuide](https://github.com/RunestoneInteractive/AuthorGuide)'. While I can see value added in a build command line parameter to specify the source root instead of relying on synergy within the files conf.py and pavement.py, at this point, this ticket is simply trying to point out that the AuthorGuide does not build (as far as I can tell).

In this repo, conf.py is not in the root, it is in the source directory. My operating assumption is that this was intended, but I have not been able to make this work without moving conf.py to the repo root.

I would send you a PR that fixes this and the minor build issues, but I am assuming that whatever process exists to automatically publish the AuthorGuide to the `runestone.academy/ns/books/published/` would break if conf.py were moved.

**Comment by bnmnetp** [comment]
No PR required.  The problem required two updates:

1. A small fix to RunestoneComponents to use the path configured in pavement to open conf.py
2. A small fix to AuthorGuide to add setup to the end of the imports on line 19.

I will make a new release of runestone with this fix later this week.
