### ISSUE TITLE
Update out of date content

### ISSUE THREAD

**Issue by DaveParillo** [RunestoneInteractive/AuthorGuide#7]
The current version of the author guide contains some build errors and broken links:

- The quick reference documents an old version of the runestone CLI
- Instructor guide should point to [its new location](https://runestone.academy/ns/books/published/instructorguide/frontmatter-1.html). This change needs to be made in ``instructor_users.rst`` and in the help menu.
- Compile errors and warnings:
   > source/conf.py:238: ERROR: Unexpected indentation. (in comment)
   WARNING: html_static_path entry '_static' does not exist
   source/developer.rst:2: WARNING: Duplicate explicit target name: "here".
   source/source/directives/df_examples/datafile_ex0.txt.rst:1: ERROR: Invalid divid 'ex0.txt'. (there are several of these)
   source/directives/pa_examples/parson_ex_maxdist.txt:12: WARNING: Definition list ends without a blank line; unexpected unindent.
- link should be made anonymous: `source/intro.rst:2: WARNING: Duplicate explicit target name: "github".`
- link missing space at end of directive: `source/faq.rst:48: WARNING: Inline interpreted text or phrase reference start-string without end-string.`
- Other broken links:

  - intro.rst:  'the overview' and 'Runestone Home'
  - directives.rst: [WAI/eval/Overview](https://www.w3.org/WAI/eval/Overview)
  - server_hackers.rst: [Flask](http://www.pocoo.org/flask) 
  - navbar: navigation help
  - IMHO, the author guide 'report a problem' should link to this repo, not RunestoneServer

**Comment by DaveParillo** [comment]
I plan to submit a PR for these.

**Comment by bnmnetp** [comment]
Thanks @DaveParillo 

I appreciate your efforts in the past and willingness to update the docs.  I also want to make sure that you know that the future for authoring is PreTeXt. https://pretextbook.org

Our missions are fully aligned and Rob is a great partner.  Plus we get the benefit of all of their work on accessibility as well as multiple formats for books including PDF, ePub, braille and others, while preserving all of the interactivity of RST.

**Comment by DaveParillo** [comment]
I saw some pretext stuff in the directives section when I updated my runestone install, but it did not look complete (just a handful of directives integrated). Do you have a roadmap? Should I hold off on updating the AuthorGuide until pretext is more fully integrated?

**Comment by DaveParillo** [comment]
Minor comment. The help says the usage is:

> Usage: runestone [--version] subcommand

but --version displays the version and exits.  What is the point to a subcommand after version?

**Comment by bnmnetp** [comment]
We have converted some books to PreTeXt already but it will probably take until next fall to complete the transition to PreTeXt as the authoring language.

See https://pretextbook.org The major directives have been integrated and we are working on the remaining and in some cases using different strategies.

**Comment by bnmnetp** [comment]
The activecode and others should be working again... Lots of out of date stuff in the author guide.  Another good reason to have a dedicated team for the authoring language.... they do a good job of keeping their docs up to date.

**Comment by DaveParillo** [comment]
So does this mean that the "native language" for books going forward will be xml instead of rst? I am a fan of the features and accessibility, but XML is probably my least favorite text specification. Perhaps because I had to deal with so many poorly designed schemas over the years. 

Or is the idea to continue authoring in rst and use rs2ptx? Or is rs2ptx a tool just for the transition?
I'm wondering partly b/c I use several sphinx plugins (matplotlib and graphviz are two) and wonder how this might impact my books.

**Comment by bnmnetp** [comment]
There are simply not enough hours in a day/week/pick-your-timeperiod to maintain An authoring language, as well as javascript to support the interactives plus all of the work for the runestone server platform.   I was not a fan of XML initially but I am a convert.

I think you will find there are alternatives that will work well for graphing, but I encourage you to stop in to one of our Drop ins and chat with Rob and I.  He is very responsive when it comes to helping authors get to where they want to be.  My hunch is that matplotlib is supported by sageplot and that if graphviz is not supported it could be.  There is also ongoing work for a much more user friendly editor for PreTeXt that will hide the xml from the author.

So.. from my perspective going forward PreTeXt is the official language.  

We will continue to support the current books until they are converted, but I don't see myself adding any new directives.

The rs2ptx tool is for a one time conversion and does a reasonable job of getting most things converted.  Some things unfortunately are really difficult to automate so there is some manual work to be done to get a satisfactory conversion ready for publication.

**Comment by DaveParillo** [comment]
Thanks for the clarification.
Where are the runestone features within pretext be documented?

**Comment by bnmnetp** [comment]
Here:  https://pretextbook.org/doc/guide/html/topic-interactive-exercises.html
and in this chapter of the annotated sample book:  https://pretextbook.org/examples/sample-book/annotated/activecode.html

**Comment by DaveParillo** [comment]
Awesome, thanks.
A quick scan of the pretext docs seems like sage is the answer to both.
Sage is built on top of matplotlib, so I'm sure anything I'm currently doing in matplotlib can be easily ported.
Some does appear to have support for graphviz, but still noodling out how that might work.
What I really want to avoid if possible is generating svg using dot commands and then incorporating svg into the book.
Perhaps a 'drop in' is just what the doctor ordered!
Thanks for all the support.
